# Generated by Django 6.0.7 on 2026-07-30 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('tenure_months', models.IntegerField()),
                ('employment_status', models.CharField(choices=[('EMP', 'Employed'), ('UNEMP', 'Unemployed')], max_length=10)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_loans', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('application_status', models.CharField(choices=[('SUB', 'Submitted'), ('VF', 'Verifying'), ('UNDR', 'Under Review'), ('SCH', 'Scheduled'), ('AP', 'Approved'), ('REJ', 'Rejected'), ('DIS', 'Disbursed')], default='SUB', max_length=10)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_tier', models.IntegerField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to=settings.AUTH_USER_MODEL)),
                ('loan_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportingDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('GHANA', 'Ghana Card'), ('NATIONAL', 'National Id'), ('FIN', 'Financial Statement'), ('OT', 'Other')], max_length=10)),
                ('document', models.FileField(upload_to='loan/documents/')),
                ('verification_status', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loan.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
