# Generated by Django 6.0.7 on 2026-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='passport_picture',
            field=models.ImageField(default=1, upload_to='loan/passport_pictures/'),
            preserve_default=False,
        ),
    ]
